### ISSUE TITLE
Colour Codes

### ISSUE THREAD

**Issue by gaiterjones** [ilias-sp/Twitch-Chat-Bot-PHP#1]
Not really an issue - more a question. Do you know how to format the bot response string in PHP to send colour code information to change the foreground or background colour of IRC messages the bot sends to chat?

Your bot code has been very useful for me - thanks!

**Comment by ilias-sp** [comment]
hi!

unfortunately no, i haven't spent any time towards that direction. i did some sniffing now to a channel, and here are my findings:

- font color: you can add the "/me" prefix to the message. The nightbot is doing it somehow differently, i could see in the log some "binary" chars, displayed with ^A below:

`:nightbot!nightbot@nightbot.tmi.twitch.tv PRIVMSG #streamer_channel :Sogomn -> The command "!score" has been edited successfully.`

`:nightbot!nightbot@nightbot.tmi.twitch.tv PRIVMSG #streamer_channel :^AACTION hugs Sogomn^A`

`:nightbot!nightbot@nightbot.tmi.twitch.tv PRIVMSG #streamer_channel :^AACTION pushes sogom away^A`

`:nightbot!nightbot@nightbot.tmi.twitch.tv PRIVMSG #streamer_channel :BacT's worst nightmare`

- Background color, you mean the message sent out from Twitch about new sub notification? the only message i captured from the bot is a USERNOTICE message:

`:tmi.twitch.tv USERNOTICE #streamer_channel :I wanted to sub to Daut, don't know what happened`

the rest of the message (username subbed for X months) doesnt appear captured, i guess its not sent via IRC?

hope these help!

**Comment by gaiterjones** [comment]
OK, well twitch IRC certainly doesn't use any standard colour codes as documented in other irc server/clients.

I found this https://dev.twitch.tv/docs/irc

and tried something like this

`$this->send_text_to_server('bot', '@color=#0D4200 PRIVMSG ' . $channel . ' :' . $message);`

But it doesn't seem to do anything...

**Comment by ilias-sp** [comment]
yes, i read the link you provided, and seems these are IRC v3 tags, and require "elevation" during initial connect. 

`CAP REQ :twitch.tv/tags`

i added this command to the `_login_to_twitch()` function, i made a few attempts with the provided example for PRVMSG scenario, but didn't succeed to see it working. tag syntax you provided seems correct, but probably need to populate more fields. if you want to inspect further, modify login_to_twitch function:

$this->send_text_to_server('service', 'PASS ' . $this->oath_pass);
        usleep(1000000);
        $this->send_text_to_server('service', 'NICK ' . $this->nickname);
        usleep(1000000);
        $this->send_text_to_server('service', 'CAP REQ :twitch.tv/membership');
        usleep(1000000);
        $this->send_text_to_server('service', 'CAP REQ :twitch.tv/commands');
        usleep(1000000);
`        $this->send_text_to_server('service', 'CAP REQ :twitch.tv/tags');`
`        usleep(1000000);`
        $this->send_text_to_server('service', 'JOIN ' . $this->channel);
        $this->logger->log_it('INFO', __CLASS__, __FUNCTION__, 'Login commands were sent. Bot is ready.');
        //
        return TRUE;

open the logs and you will see examples of the command syntax

hope it helps, please ping if you get any luck with it !

**Comment by gaiterjones** [comment]
Well this is frightfully frustrating. I guess it is not possible to set the IRCv3 tags from the client.

I tried this for example:
`$this->send_text_to_server('bot', '@badges=moderator/1;color=#FF0000;display-name=mybot;emote-sets=0;mod=1;subscriber=0;user-type=mod;user-type= :mybot!mybot@mybot.tmi.twitch.tv PRIVMSG ' . $channel . ' :' . $message);`

But then I see no response at all. The closest I have come is:
```
$this->send_text_to_server('bot', 'PRIVMSG ' . $channel . ' :/color red');
$this->send_text_to_server('bot', 'PRIVMSG ' . $channel . ' :/me ' . $message);
```

Which changes the client (bot) colour and then uses /me as you first suggested - but it's a pretty stoopid way of doing it if you ask me...

**Comment by ilias-sp** [comment]
indeed it is frustrating... perhaps you should try the dev.twitch forums
for clarifications on it, citing the examples provided in the documentation.

good luck!

**Comment by gaiterjones** [comment]
Will do, I will close this now!
