### ISSUE TITLE
I guess it's dead

### ISSUE THREAD

**Issue by MaestroMagnifico** [ilias-sp/Twitch-Chat-Bot-PHP#10]
```
IZYBOT\lib\Twitchapi: API call to get returned with error. Exiting..
Fatal error: Uncaught Exception: API call to get returned with error. Exiting.. in C:\MyStuff\WORK\OSPanel\domains\twitch\www\lib\TwitchAPI.php:353 Stack trace: #0 C:\MyStuff\WORK\OSPanel\domains\twitch\www\lib\TwitchAPI.php(92): IZYBOT\lib\Twitchapi->_get_channel_data() #1 C:\MyStuff\WORK\OSPanel\domains\twitch\www\lib\TwitchAPI.php(62): IZYBOT\lib\Twitchapi->_read_channel_data() #2 C:\MyStuff\WORK\OSPanel\domains\twitch\www\lib\IzyBot.php(134): IZYBOT\lib\Twitchapi->__construct(Array, Object(IZYBOT\lib\Logger)) #3 C:\MyStuff\WORK\OSPanel\domains\twitch\www\startIzyBot.php(38): IZYBOT\lib\IzyBot->__construct(Array) #4 {main} thrown in C:\MyStuff\WORK\OSPanel\domains\twitch\www\lib\TwitchAPI.php on line 353
```
I'm getting this error. I checked lib\TwitchAPI.php and it works with old kraken API. I'm not sure if it's still maintained or not. Will you update your bot for new helix API?

**Comment by ilias-sp** [comment]
hi,

Well yes, it hasn't been updated to work with Helix API. i will give it a look during weekend, and hopefully will not be *too* much of a big deal to update it.

cheers

**Comment by ilias-sp** [comment]
hello!

Updates were done, can you please download the new version, test and let me know if you face any problems? please take a look at the `https://github.com/ilias-sp/Twitch-Chat-Bot-PHP/blob/master/documentation/Using_Twitch_API.md` page. In brief, you need two have 1 Oath token for accessing the Twitch IRC Chat, and 1 for the Twitch API.

cheers

**Comment by MaestroMagnifico** [comment]
Works great, thanks!
How do you suggest to use it under Ubuntu? Just run startIzyBot.php once when system starts?
