### ISSUE TITLE
Online Bot

### ISSUE THREAD

**Issue by JzTurrini** [ilias-sp/Twitch-Chat-Bot-PHP#11]
Could I put this code in a regular domain and use the same bot in multiple channels?

**Comment by ilias-sp** [comment]
hello!

it was designed as a single instance bot, reading always from the same config files. with some minimum effort you can tweak it to read different config file and achieve your goal.

as for running on a hosted environment, you will need to think how to spawn the bot process and keep that process alive, but definitely its do-able.

cheers

**Comment by JzTurrini** [comment]
Thanks!
