### ISSUE TITLE
How can we integrate bot to multiple chat?

### ISSUE THREAD

**Issue by oralunal** [ilias-sp/Twitch-Chat-Bot-PHP#12]
Is there a simple trick that makes the bot follow multiple chat?

**Comment by ilias-sp** [comment]
hello!

i am afraid that's not supported.

**Comment by oralunal** [comment]
Can you guide me to the any sources that can help me to figure it out.

**Comment by pippinsmith** [comment]
I'd suggest adapting https://github.com/ilias-sp/Twitch-Chat-Bot-PHP/blob/master/lib/IzyBot.php#L950 to support multiple channels
then you can get the channel name in https://github.com/ilias-sp/Twitch-Chat-Bot-PHP/blob/master/lib/IzyBot.php#L553
