### ISSUE TITLE
API call to get returned with error

### ISSUE THREAD

**Issue by kodersha** [ilias-sp/Twitch-Chat-Bot-PHP#13]
I try start bot, but I have error:

```
php startIzyBot.php
IZYBOT\lib\Twitchapi: API call to get returned with error. Exiting..
PHP Fatal error:  Uncaught Exception: API call to get returned with error. Exiting.. in /home/a0568751/domains/twitch.fixel.ru/public_html/lib/TwitchAPI.php:353
Stack trace:
#0 /home/a0568751/domains/twitch.fixel.ru/public_html/lib/TwitchAPI.php(92): IZYBOT\lib\Twitchapi->_get_channel_data()
#1 /home/a0568751/domains/twitch.fixel.ru/public_html/lib/TwitchAPI.php(62): IZYBOT\lib\Twitchapi->_read_channel_data()
#2 /home/a0568751/domains/twitch.fixel.ru/public_html/lib/IzyBot.php(134): IZYBOT\lib\Twitchapi->__construct(Array, Object(IZYBOT\lib\Logger))
#3 /home/a0568751/domains/twitch.fixel.ru/public_html/startIzyBot.php(38): IZYBOT\lib\IzyBot->__construct(Array)
#4 {main}
  thrown in /home/a0568751/domains/twitch.fixel.ru/public_html/lib/TwitchAPI.php on line 353
```

API keys in channel_credentials.php correct

**Comment by ilias-sp** [comment]
hello!

can you check in the logs folder, for a file "IzyBot_TwitchAPI_2021-<month>-<day>.txt" and check its contents? in my PC, it looks like:

```
[http_offline@greenhat-34 log] > less IzyBot_TwitchAPI_2021-09-24.txt 
[2021-09-24 21:50:12.943695] [debug] IZYBOT\lib\AppDataHandler\ReadAppDatafile: - File: twitch_channel_data.cfg was successfully read.
[2021-09-24 21:50:12.968889] [info] IZYBOT\lib\Twitchapi\_read_channel_data: - Twitch channel ID = 76074759
[http_offline@greenhat-34 log] > 
```

thanks

**Comment by ilias-sp** [comment]
hello!

Looks like Twitch API deprecated some API endpoint, you can see the log file under `log` directory: `IzyBot_TwitchAPI_2021-09-<day of the month>.txt`

Checking what has to be done, need to update the bot's code.

**Comment by ilias-sp** [comment]
hey!

Took the decision to remove the twitch API capabilities, this removes three commands:

- set game of stream
- set title of stream
- check if a viewer is channel's subscriber.

Please get the new release [4.0.3](https://github.com/ilias-sp/Twitch-Chat-Bot-PHP/releases/tag/v4.0.3)

if you still face issues, please let me know.

cheers
