### ISSUE TITLE
Processing Messages

### ISSUE THREAD

**Issue by xSevithx** [ilias-sp/Twitch-Chat-Bot-PHP#7]
Curious here as to why on user commands your doing;
        elseif ($message_text === $this->bot_config['giveaway_join_keyword'])
and
        elseif ($words_in_message_text[0] === $this->bot_config['quote_keyword'])

I have noticed some commands are not being picked up and I am wondering if its because of the way it processes user messages. All Admin commands are using '$words_in_message_text[0]' and SOME user commands are using $words_in_message_text[0] some are using $message_text.

So the question is why use message_text and not the first element of the array? Only my admin users can place bets, regular users cannot for some weird reason. It has trouble picking them up. So I can't find why this isn't processing them correctly and this is the only thing I cant think of.

**Comment by ilias-sp** [comment]
hi and thanks for pointing that out!

it seems the `bet_place_keyword` for regular users was buggy - too much copy-paste from the neighboring if-else loops.

you are right, that i am using different condition each time, it depends on if the in question command is expected to have more than words, but i guess you figured it out. 

i patched it now, but if you fell into any other issues, plz do let me know.

cheers!

**Comment by xSevithx** [comment]
No problem. I actually replaced them all with $words_in_message_text[0] and it seems to be working perfect now.
My real question is if this can handle thousands of concurrent requests (For betting in particular)?

**Comment by ilias-sp** [comment]
unfortunately, i cant answer that. the loop will parse all the messages it receives in each loop, i wouldnt expect it to have a problem, but cant say it ..

in line 400 of `IzyBot.php`, there is a `sleep(1)` (i.e 1 second interval). if you are having a really high traffic, i would decrease that value to a smaller one. maybe set it to `usleep(300000);`.

but i guess you would see some errors if your load is that much PHP cannot handle the incoming messages.
