### ISSUE TITLE
Requirement of PHP version?

### ISSUE THREAD

**Issue by seonghobae** [ilias-sp/Twitch-Chat-Bot-PHP#8]
Hello,
I want to know requirements of PHP version to run this app appropriately.

Best,
Seongho

**Comment by ilias-sp** [comment]
hi,

Assuming you want to run it on windows, any recent PHP should do it. In my 64bit Windows, i am having:

C:\Users\dev10>php --version
PHP 7.1.3 (cli) (built: Mar 14 2017 23:33:39) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

which was downloaded with php-7.1.3-Win32-VC14-x64.zip

**Comment by seonghobae** [comment]
I'm running on Ubuntu Linux, PHP 7.2

**Comment by ilias-sp** [comment]
it will work fine on Linux and your PHP version. i am writing it and testing in on Linux too.
