### ISSUE TITLE
Add Admin

### ISSUE THREAD

**Issue by H4nSolo** [ilias-sp/Twitch-Chat-Bot-PHP#9]
How i can add a Admin User in the Admin_Username.cfg manually and what is the syntax of the file?

Is it possible to add Admins in the Webinterface of the Bot?

**Comment by ilias-sp** [comment]
hey!

the web UI is "read only"

to add admins manually, just add a few via the `!addadmin` command, then inspect the file with a text editor like notepad++ and you will figure out how to do it by editing the file.

thx
